channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip<=25.1
  - pip:
      - mlflow==2.18.0
      - cloudpickle==3.1.1
      - numpy==2.2.6
      - pandas==2.2.3
      - psutil==7.0.0
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - xgboost==1.7.6
name: mlflow-env