name: CI/CD MLflow

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/preprocessed_data/car_evaluation_train_dataset.csv"
  TARGET_VAR: "Car_Evaluation"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Miniconda & create environment from conda.yaml
      - name: Set up Conda and create env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          python-version: 3.12.7

      # Check Env Variables
      - name: Check Env
        run: |
            echo $CSV_URL

      # Install mlflow
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Run MLflow with conda env
      - name: Run as MLflow Project (with conda env)
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          mlflow run MLProject --env-manager=local

      # get latest run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | grep -v 'datasets' | head -n 1 | xargs basename)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Debug MLflow directory
        run: |
          echo "Run ID: $RUN_ID"
          ls -R mlruns/0/$RUN_ID

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Move mlruns directory into MLProject
        run: mv mlruns MLProject/

      - name: Commit and push MLflow artifacts
        run: |
          git add mlruns/0/$RUN_ID/artifacts/model/
          git diff --cached --quiet || git commit -m "chore: add MLflow model artifacts for run $RUN_ID"
          git push origin main

      # Build docker model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "car-eval"

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag car-eval ${{ secrets.DOCKER_HUB_USERNAME }}/car-eval:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/car-eval:latest
      