name: CI/CD MLflow

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/preprocessed_data/car_evaluation_train_dataset.csv"
  TARGET_VAR: "Car_Evaluation"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # # Setup Python 3.12.7
      # - name: Setup Python 3.12.7
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.12.7

      # Setup Miniconda & create environment from conda.yaml
      - name: Set up Conda and create env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false
          python-version: 3.12.7

      # Check Env Variables
      - name: Check Env
        run: |
            echo $CSV_URL

      # Install mlflow
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # # Run as a mlflow project
      # - name: Run as MLfLow Project
      #   run: |
      #     mlflow run MLProject --env-manager=local

      # Run MLflow with conda env
      - name: Run as MLflow Project (with conda env)
        shell: bash -l {0}
        run: |
          conda activate mlflow-env
          mlflow run MLProject --env-manager=local

      # get latest run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # Build docker model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "car-eval"

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag car-eval ${{ secrets.DOCKER_HUB_USERNAME }}/car-eval:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/car-eval:latest
      
